GET http://localhost:3001/

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6885547aca6a66fbd1b037ab

###
GET http://localhost:3001/api/persons/6885547aca6a66fbd1b037ac

###
GET http://localhost:3001/api/persons/5